### ISSUE TITLE
GraphQL query issues

### ISSUE THREAD

**Issue by james075** [strapi/strapi-starter-gatsby-blog#10]
Hi guys, Thank you so much for your work on strapi, it's awesome.

Following this tutorial https://strapi.io/blog/strapi-starter-gatsby-blog

I have set up the [backend](https://github.com/strapi/strapi-legacy-blog), which is up and running well; however, I have plenty of errors when I run the front-end.

Is there any configuration I missed?

![image](https://user-images.githubusercontent.com/5047120/97035898-02d69780-1535-11eb-9277-e1ce747bd0c7.png)
![image](https://user-images.githubusercontent.com/5047120/97035929-0a963c00-1535-11eb-8daf-c7d788382acf.png)

**Comment by remidej** [comment]
Hello!

It looks like the article you followed is outdated.

Can you try following the instructions on this repo's readme and tell me if it works?

**Comment by james075** [comment]
I was misled by the tutorial, I didn't use the right backend template! Following the instructions from this readme, it works really well. Thanks

**Comment by remidej** [comment]
Thanks for the heads up, we should definitely fix that article

**Comment by purnimagupta** [comment]
@james075, @remidej, I'm also trying to run the instructions mentioned here in the Readme file which after running creates two folders - _frontend_ and _backend_. I ran `npm run develop` to run both the repos as mentioned in the `package.json` file at the root.

Strapi Admin automatically starts at `localhost://1337` but the frontend(Gatsby) fails to run. I'm running into GraphQL query issues like the below:

```
   File: src/pages/category/{StrapiCategory.slug}.js:9:46

  GraphQLError: Field "category" is not defined by type "StrapiArticleFilterInput".
  
  ---
  There was an error in your GraphQL query:

  Cannot query field "image" on type "StrapiArticle".

  File: src/pages/article/{StrapiArticle.slug}.js:16:7

  ---
  Cannot query field "author" on type "StrapiArticle".
  File: src/pages/article/{StrapiArticle.slug}.js:22:7

 ---
  Cannot query field "author" on type "StrapiArticle".
  File: src/pages/index.js:50:11

 ---
Can't resolve '../../public/page-data/sq/d/2852343550.json' in '/home/purnima/projects/gatsby_strapi/my-site/frontend/src/pages'
  
```

I'm very new to GraphQL so it's getting difficult for me to debug it. Can someone point out what could go wrong here?
