### ISSUE TITLE
ERROR #11331  PLUGIN  Invalid plugin options for "gatsby-plugin-manifest"

### ISSUE THREAD

**Issue by jacktho** [strapi/strapi-starter-gatsby-blog#15]
Hello, I am unable to build the frontend. I get the following error:
```

ERROR #11331  PLUGIN

Invalid plugin options for "gatsby-plugin-manifest":

- "value" must contain at least one of [icon, icons]
```

**Comment by jacktho** [comment]
I'm able to avoid the error by downgrading “gatsby-plugin-manifest” to 2.4.37.

https://github.com/gatsbyjs/gatsby/issues/27839

**Comment by LukaEHB** [comment]
`npm install gatsby-plugin-manifest@2.4.37`

**Comment by markkaylor** [comment]
Although it's not clearly documented: https://www.gatsbyjs.com/plugins/gatsby-plugin-manifest/ I believe `icon` is a required option.  At least that is what is stated here:

https://github.com/gatsbyjs/gatsby/issues/28312

For https://github.com/strapi/strapi-starter-gatsby-catalog/blob/main/frontend/gatsby-config.js I had a similar issue and left the icon/favicon even though I'm not using it.

However I just did a fresh install of this starter with `gatsby-plugin-manifest v2.4.5` and had no issues.  

@jacktho  If you found a workaround for your issue are we good to close?

**Comment by markkaylor** [comment]
https://github.com/strapi/strapi-starter-gatsby-blog/pull/18 and https://github.com/strapi/strapi-starter-gatsby-blog/pull/11

Should resolve this issue.  Closing.
