### ISSUE TITLE
constantly getting 404

### ISSUE THREAD

**Issue by ItsMeStevieG** [strapi/strapi-starter-gatsby-blog#16]
I deployed this to both Heroku and Netlify following instructions here https://www.netlify.com/blog/2020/08/11/deploy-a-strapi-and-react-blog-on-netlify/ and I am getting "Page Not Found
Looks like you've followed a broken link or entered a URL that doesn't exist on this site." on netlify.

I renamed to .env and added the config correctly as the guide suggested.

Any help would be greatly appreciated

**Comment by markkaylor** [comment]
Are you able to fetch data from your heroku endpoint?  Does your build on netlify succeed?  

Could you provide any logs from heroku / netlify?

Could you take a look at these two suggestions:
https://answers.netlify.com/t/support-guide-i-ve-deployed-my-site-but-i-still-see-page-not-found/125
https://answers.netlify.com/t/support-guide-i-ve-deployed-my-site-but-i-still-see-page-not-found/125/2

The build command and directory for a gatsby site are shown here on step 5: https://www.netlify.com/blog/2016/02/24/a-step-by-step-guide-gatsby-on-netlify/

**Comment by remidej** [comment]
I'm going to close this as it's been a few weeks, and we don't have the info necessary to reproduce the issue.

@ItsMeStevieG I can reopen it if you provide more details
