### ISSUE TITLE
Please Update dependencies to latest version of strapi/gatsby

### ISSUE THREAD

**Issue by ItsMeStevieG** [strapi/strapi-starter-gatsby-blog#17]

**Comment by Pedromigacz** [comment]
Have you found any updated version?

**Comment by Pedromigacz** [comment]
Have you found any updated version?

**Comment by markkaylor** [comment]
https://github.com/strapi/strapi-starter-gatsby-blog/pull/22 All dependencies should be up to date.  closing.
