### ISSUE TITLE
Homepage url linked to open directory

### ISSUE THREAD

**Issue by prateekkarki** [strapi/strapi-starter-gatsby-blog#5]
The homepage url for repo [strapi-starter-gatsby-blog-v2.vercel.app](strapi-starter-gatsby-blog-v2.vercel.app) points to an open directory and does not serve any purpose.  This should be pointed to a hosted version of strapi blog.

**Comment by markkaylor** [comment]
Hi @prateekkarki I believe this issue has been resolved.  

Where did you find the problem?  

The url provided in the about of this repo is: https://strapi-starter-gatsby-blog-orcin.vercel.app .  It links to a hosted version of the blog.  All links appear to be working on the site. 

I'm closing this issue, but if you still have problems please let us know. Thanks!
