### ISSUE TITLE
404 error on the project website

### ISSUE THREAD

**Issue by teinett** [strapi/strapi-starter-gatsby-blog#9]
This starter has example URL: https://strapi-starter-gatsby-blog-v2.vercel.app/

Now there is an error on the page:

```
404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: arn1::hkxr2-1601988864188-cff65b9a0e41

NOTE: strapi-starter-gatsby-blog-v2.vercel.app might be available. Click here to learn how to assign it to a project.

```

Screenshot is attached.

![image](https://user-images.githubusercontent.com/1038168/95204284-90538100-07ec-11eb-9b37-bf76c6139a0a.png)

**Comment by remidej** [comment]
It's fixed, the demo is now here: https://strapi-starter-gatsby-blog-orcin.vercel.app/
